"""add_exception_ticket_timestamps

Revision ID: 210fb62aebc3
Revises: 523f204203f1
Create Date: 2026-07-29 06:29:35.503673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210fb62aebc3'
down_revision = '523f204203f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exception_ticket', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('exception_ticket', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exception_ticket', 'updated_at')
    op.drop_column('exception_ticket', 'created_at')
    # ### end Alembic commands ###
