"""init

Revision ID: 523f204203f1
Revises: 
Create Date: 2026-07-29 02:06:49.894282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523f204203f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('line',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plant',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'plant_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('station',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_no', sa.String(length=32), nullable=True),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('antivirus_status', sa.String(length=32), nullable=False),
    sa.Column('domain_status', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('inspector_id', sa.UUID(), nullable=False),
    sa.Column('inspect_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_no')
    )
    op.create_table('exception_ticket',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('current_assignee_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['current_assignee_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_table('inspection_image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exception_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('attachment_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['exception_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exception_history')
    op.drop_table('inspection_image')
    op.drop_table('exception_ticket')
    op.drop_table('inspection')
    op.drop_table('station')
    op.drop_table('user_role')
    op.drop_table('user_plant')
    op.drop_table('line')
    op.drop_table('sys_user')
    op.drop_table('role')
    op.drop_table('plant')
    # ### end Alembic commands ###
